default :
  image : immc/flups-valid:v0.2

stages:
  - build
  - test

compilation :
  stage: build
  artifacts: 
    paths: 
      - flups_validation
    when: on_success
  script:
    - echo "include make_arch/make.docker_valid" > Makefile.valid
    - tail -n +5 Makefile >> Makefile.valid
    - make -j4 -f Makefile.valid

#checks that the code runs without error
run test 1:1:
  stage: test
  script:
    - ./flups_validation -ns 1
  dependencies: 
    - compilation

run test 2:1:
  stage: test
  script:
    - mpirun -np 4 ./flups_validation -np 2 2 1 -res 32
  dependencies: 
    - compilation

#validation all types of BCs with 1 kernel
validation all BCs:
  stage: test
  script:
    - python3.7 ./scripts/test_bcs.py
  dependencies: 
    - compilation
