default :
  image : immc/flups-valid:v0.2

stages:
  - build
  - test

compil dbg :
  stage: build
  artifacts: 
    paths: 
      - flups_validation
    when: on_success
  script:
    - echo "include make_arch/make.docker_valid_dbg" > Makefile.valid
    - tail -n +5 Makefile >> Makefile.valid
    - make -j4 -f Makefile.valid

compil opt :
  stage: build
  artifacts: 
    paths: 
      - flups_validation
    when: on_success
  script:
    - echo "include make_arch/make.docker_valid_opt" > Makefile.valid
    - tail -n +5 Makefile >> Makefile.valid
    - make -j4 -f Makefile.valid

#checks that the code runs without error
run serial 1:1:
  stage: test
  script:
    - ./flups_validation -ns 1
  dependencies: 
    - compil dbg

run parallel 1:1:
  stage: test
  script:
    - mpirun -np 4 ./flups_validation -np 2 2 1 -res 32
  dependencies: 
    - compil dbg

#validation all types of BCs with 1 kernel
validate3D all BCs:
  stage: test
  script:
    - python3.7 ./scripts/test_3D_bcs.py
  dependencies: 
    - compil opt

# converge3D all kernels :
#   stage: test
#   script:
#     - python3.7 ./scripts/test_3D_kerns.py
#   dependencies: 
#     - compil opt